name: omop_public_health
version: "0.1.0"
config-version: 2
profile: omop_showcase

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  raw_dir: "../data/raw"

models:
  omop_public_health:
    staging:
      +materialized: view
    marts:
      +materialized: table
